spring.application.name=ai

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.flrzlulvyzokzwptsidz
spring.datasource.password=Ljp136174298

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.ai.deepseek.api-key=${DEEPSEEK_API_KEY}

springdoc.swagger-ui.tryItOutEnabled=true

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=0