begin;

create table if not exists public.album_item (
  id bigint generated by default as identity primary key,
  album_id bigint not null references public.album(id) on delete cascade,
  name text not null,
  alternative_names jsonb not null default '[]'::jsonb,
  estimated_amount text not null default '份量不明',
  created_at timestamptz not null default now(),

  constraint album_item_name_not_blank
    check (length(btrim(name)) > 0),
  constraint album_item_alternative_names_is_array
    check (jsonb_typeof(alternative_names) = 'array')
);

-- Also upgrades an existing table created from the previous version of this DDL.
alter table public.album_item drop column if exists sort_order;

-- Equivalent to creating the table in Supabase Dashboard with RLS unchecked.
-- Realtime stays disabled because the table is not added to supabase_realtime.
alter table public.album_item disable row level security;
grant usage on schema public
  to anon, authenticated, service_role;
grant all privileges on table public.album_item
  to anon, authenticated, service_role;
grant all privileges on sequence public.album_item_id_seq
  to anon, authenticated, service_role;

create index if not exists album_item_album_id_idx
  on public.album_item (album_id);

comment on table public.album_item is 'AI 从相册图片中识别出的组成明细';
comment on column public.album_item.alternative_names is '备选名称字符串数组，例如 ["意面", "番茄意大利面"]';
comment on column public.album_item.estimated_amount is '视觉预估量，例如约 200 克、1 碗、2 个';

commit;
